//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Applications
    {
        public int IdApp { get; set; }
        public string JobTitle { get; set; }
        public string CmpName { get; set; }
        public string JsName { get; set; }
        public string CV { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> JsId { get; set; }
        public string CompanyLogo { get; set; }

        public HttpPostedFileBase CVFile { get; set; }

        public virtual JobPost JobPost { get; set; }
        public virtual JobSeekerProfile JobSeekerProfile { get; set; }
    }
}
