//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class CompanyProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyProfile()
        {
            this.Blog = new HashSet<Blog>();
            this.JobPost = new HashSet<JobPost>();
        }
    
        public int CmpId { get; set; }
        public string CmpName { get; set; }
        public string CmpHeadQ { get; set; }
        public string CmpFounded { get; set; }
        public string CmpFounders { get; set; }
        public string CmpCeo { get; set; }
        public string CmpEmail { get; set; }
        public string CmpContact { get; set; }
        public string CmpWebsite { get; set; }
        public string CmpDescription { get; set; }
        public string CmpLogo { get; set; }
        public string CmpPassword { get; set; }
        public string CmpNewPassword { get; set; }

        public HttpPostedFileBase Cover { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blog> Blog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPost> JobPost { get; set; }
    }
}
