//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CareerCareDBEntities : DbContext
    {
        public CareerCareDBEntities()
            : base("name=CareerCareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<CompanyProfile> CompanyProfile { get; set; }
        public virtual DbSet<JobPost> JobPost { get; set; }
        public virtual DbSet<JobSeekerProfile> JobSeekerProfile { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<BlogComments> BlogComments { get; set; }
    }
}
