//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPost()
        {
            this.Applications = new HashSet<Applications>();
        }
    
        public int JobId { get; set; }
        public string JobTitle { get; set; }
        public string JobDes { get; set; }
        public string JobRequiredSkill { get; set; }
        public string JobExperience { get; set; }
        public string JobPostedDate { get; set; }
        public string JobLocation { get; set; }
        public string JobVacancy { get; set; }
        public string JobDeadLine { get; set; }
        public string JobSalary { get; set; }
        public string JobNature { get; set; }
        public string JobTag { get; set; }
        public Nullable<int> CmpId { get; set; }
    
        public virtual CompanyProfile CompanyProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applications> Applications { get; set; }
    }
}
