//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class JobSeekerProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobSeekerProfile()
        {
            this.Applications = new HashSet<Applications>();
        }
    
        public int JsId { get; set; }
        public string JsName { get; set; }
        public string JsEmail { get; set; }
        public string JsDateOfBirth { get; set; }
        public Nullable<int> JsPhone { get; set; }
        public string JsGender { get; set; }
        public string JsAddress { get; set; }
        public string JsPassword { get; set; }
        public string JsCurrentPosition { get; set; }
        public string JsSkills { get; set; }
        public string JsImagePath { get; set; }
        public string JsNewPassword { get; set; }

        public HttpPostedFileBase Cover { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applications> Applications { get; set; }
    }
}
